// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.0--rc3
// source: rider.proto

package rider

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderRequest) Reset() {
	*x = RiderRequest{}
	mi := &file_rider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderRequest) ProtoMessage() {}

func (x *RiderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderRequest.ProtoReflect.Descriptor instead.
func (*RiderRequest) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{0}
}

func (x *RiderRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RiderRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type RiderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderIds      []string               `protobuf:"bytes,1,rep,name=rider_ids,json=riderIds,proto3" json:"rider_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderResponse) Reset() {
	*x = RiderResponse{}
	mi := &file_rider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderResponse) ProtoMessage() {}

func (x *RiderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderResponse.ProtoReflect.Descriptor instead.
func (*RiderResponse) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{1}
}

func (x *RiderResponse) GetRiderIds() []string {
	if x != nil {
		return x.RiderIds
	}
	return nil
}

var File_rider_proto protoreflect.FileDescriptor

const file_rider_proto_rawDesc = "" +
	"\n" +
	"\vrider.proto\x12\x05rider\"H\n" +
	"\fRiderRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\",\n" +
	"\rRiderResponse\x12\x1b\n" +
	"\trider_ids\x18\x01 \x03(\tR\briderIds2L\n" +
	"\fRiderService\x12<\n" +
	"\x0fGetNearbyRiders\x12\x13.rider.RiderRequest\x1a\x14.rider.RiderResponseB\x1aZ\x18shared/proto/rider;riderb\x06proto3"

var (
	file_rider_proto_rawDescOnce sync.Once
	file_rider_proto_rawDescData []byte
)

func file_rider_proto_rawDescGZIP() []byte {
	file_rider_proto_rawDescOnce.Do(func() {
		file_rider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rider_proto_rawDesc), len(file_rider_proto_rawDesc)))
	})
	return file_rider_proto_rawDescData
}

var file_rider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rider_proto_goTypes = []any{
	(*RiderRequest)(nil),  // 0: rider.RiderRequest
	(*RiderResponse)(nil), // 1: rider.RiderResponse
}
var file_rider_proto_depIdxs = []int32{
	0, // 0: rider.RiderService.GetNearbyRiders:input_type -> rider.RiderRequest
	1, // 1: rider.RiderService.GetNearbyRiders:output_type -> rider.RiderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rider_proto_init() }
func file_rider_proto_init() {
	if File_rider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rider_proto_rawDesc), len(file_rider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rider_proto_goTypes,
		DependencyIndexes: file_rider_proto_depIdxs,
		MessageInfos:      file_rider_proto_msgTypes,
	}.Build()
	File_rider_proto = out.File
	file_rider_proto_goTypes = nil
	file_rider_proto_depIdxs = nil
}
